### ISSUE TITLE
application is freeze when compute

### ISSUE THREAD

**Issue by zoowx321** [paynterf/MagCalTool#4]
![image](https://user-images.githubusercontent.com/8641002/140002130-ae0bb960-5225-411e-a8af-f1f2ee608153.png)

collected data and run compute for calibraton but nothing happen. just freezing

how can i fix it?

**Comment by paynterf** [comment]
What version are you using? The latest version (V2.1.7) fixed a bug that caused problems with some data sets.  Also, some users reported problems when using this app where the PC's language region was set to a non-English language.  If this is your case, you might also try resetting the language region to English.
