### ISSUE TITLE
Soft-Iron matrix seems strange

### ISSUE THREAD

**Issue by RafigRzayev** [paynterf/MagCalTool#5]
Hello,

The soft-iron matrix that the program outputs has very strange values. 

When I use identity matrix for soft-iron, my yaw angle has ~5 degrees error. When I use soft-iron matrix generated by the program the angles don't make sense anymore. 

When I check other examples, most soft-iron matrices are usually similar to identity matrix by the values. 

Below you can find my output:
![10k](https://user-images.githubusercontent.com/58329539/183386310-d3a94030-915f-4983-8c8d-3dd7d3aa90b8.JPG)

Hard-iron offset values are correct. 

How this values should be used?

I expected following usage:
![Capture1](https://user-images.githubusercontent.com/58329539/183386861-2a4097bc-40e9-4a16-bce5-08788d154e9d.JPG)

I would appreciate your help.

**Comment by paynterf** [comment]
Sorry if this isn't working so well for you, but I'm not really an expert on the actual calibration routine - my program just makes calls into Alain Barraud's MATLAB program, as explained in[ this blog post](https://www.fpaynter.com/2016/04/magnetometer-calibration-part/).

However, it does look like the raw data shown in your screenshot is getting properly calibrated.  The view in the 'Calibrated' window looks quite symmetric about the origin so the calibration matrix appears to be correct (the points in the 'Calibrated' window are generated by applying the calibration matrix point-by-point).

**Comment by RafigRzayev** [comment]
Hello. 

Ok, I understand. No problems then. In case I find out anything I will post details here. 

Big thanks for the tool.
